### ISSUE TITLE
Kube pod monitor: Unable to see BLKIO when using top command Kubernetes pod

### ISSUE THREAD

**Issue by dksingh3117** [peo3/cgroup-utils#10] opened 2019-12-09 15:51 UTC
Unable to see BLKIO when using top command Kubernetes pod below is the screen shot, If anyone can help me here, If I am missing anything ?
![image](https://user-images.githubusercontent.com/28087417/70450599-02bedc00-1aca-11ea-9e3f-be959671d366.png)

cat blkio.throttle.io_service_bytes
259:0 Read 1363968
259:0 Write 16384
259:0 Sync 1363968
259:0 Async 16384
259:0 Discard 0
259:0 Total 1380352
Total 1380352

**Comment by peo3** [comment] 2019-12-12 17:28
I guess that the top command doesn't work because the latest version of cgutils (0.7) doesn't include https://github.com/peo3/cgroup-utils/commit/78444dbff12d3151f74379f2dde441375aafdefb yet which changes to read `blkio.throttle.io_service_bytes` instead of `blkio.io_service_bytes`.

I will soon make a new release but if you want to try right away, please build cgutils by yourself or directly apply the change to the deployed script (`/usr/local/lib/python3.7/dist-packages/cgutils/commands/top.py` in my environment).

Thanks.

**Comment by peo3** [comment] 2019-12-16 16:19
0.8 has been released.  Hope it works for you.

**Comment by peo3** [comment] 2020-01-25 08:03
I confirmed the fix on KGE, so close the issue.  Feel free to reopen if you still have a problem.

**Closed by peo3** 2020-01-25 08:03 UTC
